### ISSUE TITLE
"missing 1 required positional argument: 'target_audience'" when generating credentials from service file using IDTokenCredentials

### ISSUE THREAD

**Issue by charliesneath** [googleapis/google-auth-library-python#557] opened 2020-07-13 11:39 UTC
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-auth-library-python/issues

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Raspbian GNU/Linux 10 (buster)
  - Python version: 3.7
  - pip version: installed through Pipenv 11.9.0
  - `google-auth` version: 1.18.0

#### Steps to reproduce

1. Create service account with Owner privileges (for debugging) and download service key
2. Following instructions [here](https://google-auth.readthedocs.io/en/latest/reference/google.oauth2.service_account.html#google.oauth2.service_account.IDTokenCredentials) for generating credentials, write and run the code (below) and see error

```
if __name__ == '__main__':
    credentials = (
        service_account.IDTokenCredentials.from_service_account_file(
            'key.json'))
    scoped_credentials = credentials.with_scopes(
            ['https://www.googleapis.com/auth/cloud-platform'])
    authed_session = AuthorizedSession(scoped_credentials)
    response = authed_session.post(url)
```

This is essentially the same as shown in the example in the docs:

```
credentials = (
    service_account.IDTokenCredentials.from_service_account_file(
        'service-account.json'))
```

I get the following error, even though `target_audience` isn't listed as one of the keyword arguments for `IDTokenCredentials` when using the `from_service_account_file` method:

`TypeError: __init__() missing 1 required positional argument: 'target_audience'`

- - - 

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by busunkim96** [comment] 2020-07-13 17:02
Hi @charliesneath,

Thanks for the report! It looks like the documentation needs to be fixed. `target_audience` is required to make a ID Token.

https://github.com/googleapis/google-auth-library-python/blob/3dda7b2ab88aba7941b8b5281b4acbc7db74169b/tests/oauth2/test_service_account.py#L247-L267

**Comment by charliesneath** [comment] 2020-07-13 17:27
Thanks. I'm also getting an error when trying to include scope, but from the method and with a keyword argument (also demonstrated in the example).

Specifically I'm trying to add the scope for Cloud Functions: `['https://www.googleapis.com/auth/cloud-platform']`

**Comment by busunkim96** [comment] 2020-07-13 17:42
I think the documentation for ID Token must have been copy-pasted from service account. Taking a closer look at the class there are no `scopes` for an IDToken.

https://github.com/googleapis/google-auth-library-python/blob/3dda7b2ab88aba7941b8b5281b4acbc7db74169b/google/oauth2/service_account.py#L420-L443

Is there a specific reason you need to use IDTokenCredentials? You can also use a plain service account credential to create an `AuthorizedSession`.

**Comment by charliesneath** [comment] 2020-07-13 18:24
I'm trying to authenticate a service account (running from a Raspberry Pi) for access to a Cloud Function that requires authentication. Have not had any luck so far and was trying this as a way to generate the necessary token to authorize access.

Have struggled to find documentation for this flow so any guidance would be appreciated. Thank you!

NOTE: I was able to authenticate through the method outlined [here](https://developers.google.com/identity/protocols/oauth2/service-account#jwt-auth), but would prefer not to rely on this as usage limits are pretty extreme (listed [here](https://cloud.google.com/functions/quotas) using "CALL").

**Comment by busunkim96** [comment] 2020-07-13 20:59
It looks like the documentation for authenticating to cloud functions is [here](https://cloud.google.com/functions/docs/securing/authenticating). It seems like your use case is [service-to-function](https://cloud.google.com/functions/docs/securing/authenticating#service-to-function).

> 
> 1. Self-sign a service account JWT with the target_audience claim set to the URL of the receiving function.
> 
> 2. Exchange the self-signed JWT for a Google-signed ID token, which should have the aud claim set to the above URL.
> 
> 3. Include the ID token in an Authorization: Bearer ID_TOKEN header in the request to the function
> 

It looks like an ID Token is the way to go.

Does something like this work for you?

```py
credentials = service_account.IDTokenCredentials.from_service_account_file( 
         SERVICE_ACCOUNT_JSON_FILE, 
         target_audience="https://function/url/here",
 ) 

authed_session = AuthorizedSession(credentials)
response = authed_session.post(url)
```

**Comment by charliesneath** [comment] 2020-07-14 00:21
Yes, that finally worked for me! Thanks very much.

Note that when running `credentials.valid` I get `False` even if the response returns the data behind the URL requiring authentication.

**Comment by busunkim96** [comment] 2020-07-14 04:51
Hmm, the `credentials.valid` is `False` even though the token seems to be valid?

**Comment by charliesneath** [comment] 2020-07-15 00:51
Yes — I can use the credentials but I get `False` back.

**Comment by arithmetic1728** [comment] 2020-07-16 07:40
@charliesneath This is the expected behavior. `service_account.IDTokenCredentials.from_service_account_file` only creates the credentials but not the token, so it is not valid. You need to call `credentials.refresh` method to refresh/obtain the token and then it becomes valid. However, this is not necessary when you call `authed_session.post(url)`, because credentials always refreshes itself for any http call from `authed_session`.

**Comment by charliesneath** [comment] 2020-07-16 11:11
Thanks for clarifying.

**Comment by arithmetic1728** [comment] 2022-05-02 20:16
Seems the issue is already resolved. Closing the issue.

**Closed by arithmetic1728** 2022-05-02 20:16 UTC
Labels: type: docs
