### ISSUE TITLE
AttributeError: 'Credentials' object has no attribute '_quota_project_id'

### ISSUE THREAD

**Issue by vj-09** [googleapis/google-auth-library-python#408] opened 2019-12-11 11:56 UTC

**Comment by enflo** [comment] 2019-12-11 14:43
I have an application in Python that connects to Gmail to read emails, today when making a production upload to stopped working due to the update of the package. Constantly jumps the error :

```
Traceback (most recent call last):
  File "/opt/src/app.py", line 55, in <module>
    filtered_ids = GmailMailFilter(resource, google_user_id).filter_by_labels([label, mail_labels['UNREAD']])
  File "/opt/src/application/filter/GmailMailFilter.py", line 24, in filter_by_labels
    labelIds=labels).execute()
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 851, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 165, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/google_auth_httplib2.py", line 187, in request
    self._request, method, uri, request_headers)
  File "/usr/local/lib/python3.7/site-packages/google/auth/credentials.py", line 125, in before_request
    self.apply(headers)
  File "/usr/local/lib/python3.7/site-packages/google/oauth2/credentials.py", line 185, in apply
    if self.quota_project_id is not None:
  File "/usr/local/lib/python3.7/site-packages/google/oauth2/credentials.py", line 134, in quota_project_id
    return self._quota_project_id
AttributeError: 'Credentials' object has no attribute '_quota_project_id'
```

We have tried to regenerate the credentials with credential.json (result the file token.pickle) but we continue with the same error.

Any solution?

PS: we have downgraded to version 1.7.2 of the package to work around the problem.

**Comment by busunkim96** [comment] 2019-12-11 18:44
Hi! This seems to be a duplicate of #405 

Here's the guidance I provided in the other issue:

If you're running into this, please do either (1) or (2).

(1) Delete your pickled credentials file. The file will be named `token.pickle` if you followed a Google quickstart. Re-run the script (code that runs the authorization flow).
(2) Pin to a previous version `google-auth==1.7.2`

I am working on rolling this back with a new release (will be 1.8.1). Please follow up in #405 if you continue to experience problems. Thanks!

**Closed** 2019-12-11 18:51 UTC
