### ISSUE TITLE
cachetools v4 dropped support for python 2

### ISSUE THREAD

**Issue by caseyduquettesc** [googleapis/google-auth-library-python#414] opened 2019-12-17 02:17 UTC
`google-auth` depends on `cachetools` >=2 and <5 
https://github.com/googleapis/google-auth-library-python/blob/091ed16d21ce1a909e9db08d6c73c097dbb263a5/setup.py#L22

Yesterday `cachetools` released v4, which dropped support for python 2, but the most recent version of `google-auth` appears to support python 2 still.

A clean install using `pip install google-auth` will fail because 
```
egg_info for package cachetools produced metadata for project name
unknown. Fix your #egg=cachetools fragments.
```

Anyone else running into the issue, you can pin `cachetools` to `>=2.0.0,<4` until it's officially addressed.

**Comment by lgrabowski** [comment] 2019-12-20 08:04
I can confirm that I found multiple workloads failing due to unable to finish the work (upload to gcs) or even initialize (import google-auth)

**Comment by busunkim96** [comment] 2020-01-28 17:57
cachetools 4.0.0 has an explicit `python_requires` in the [setup.cfg](https://github.com/tkem/cachetools/blob/master/setup.cfg#L27), so you should get the highest compatible version. `python_requires` was added more recently, so you may need to upgrade your pip and python_requires if you haven't recently. 

Would someone on this thread mind trying the upgrade and letting me know if that resolves the issue?
`pip install --upgrade pip`
`pip install --upgrade setuptools`

https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

> Note Support for this feature is relatively recent. Your project’s source distributions and wheels (see Packaging your project) must be built using at least version 24.2.0 of setuptools in order for the python_requires argument to be recognized and the appropriate metadata generated.
In addition, only versions 9.0.0 and higher of pip recognize the python_requires metadata. Users with earlier versions of pip will be able to download & install projects on any Python version regardless of the projects’ python_requires values.

**Comment by parthea** [comment] 2021-08-09 20:18
I'm going to close this as obsolete as python 2 is no longer supported in [setup.py](https://github.com/googleapis/google-auth-library-python/blob/master/setup.py#L57) of the default branch.

**Closed by parthea** 2021-08-09 20:18 UTC
Labels: type: question
