### ISSUE TITLE
1.11.1 released a backwards incompatible breaking change in a patch version

### ISSUE THREAD

**Issue by danking** [googleapis/google-auth-library-python#445] opened 2020-02-14 16:58 UTC
- [x] Search the issues already opened: https://github.com/googleapis/google-auth-library-python/issues

The bug is reported in #443. I'm opening this ticket to specifically request a discussion about how to avoid breaking changes in a patch version. The PR that introduced the change is #365. The release of that change as 1.11.1 was PR #437 . It looks like there needs to be a test that a valid token can be decoded?

**Comment by busunkim96** [comment] 2020-02-14 17:27
@danking Yes, it looks like we need a system test against the live endpoint. 

I made two bad assumptions here, that the `v1` and `v3` endpoints returned the same payload, and that the codebase already had a test for it. I'll use this issue to track the addition of the test.

Thanks for filing an issue!

**Comment by danking** [comment] 2020-02-14 17:35
Thanks @busunkim96 !

**Comment by arithmetic1728** [comment] 2022-04-08 18:17
seems the problem is already solved, closing the issue

**Closed by arithmetic1728** 2022-04-08 18:17 UTC
Labels: type: process
