### ISSUE TITLE
Dependency chain did not install `rsa`

### ISSUE THREAD

**Issue by michaelblyons** [googleapis/google-auth-library-python#720] opened 2021-03-11 15:39 UTC
#### Environment details

  - **OS:** MacOS Catalina
  - **Python version:** 3.7
  - **pip version:** Pipenv 2020.11.15
  - **`google-auth` version:** Unsure how to find this.

#### Steps to reproduce

Basically it's the return of #548, but I think it just didn't install `rsa` as a dependency.

  1. `pip install google-auth-oauthlib`
  1. `python -c "from google.auth.crypt import _cryptography_rsa"`

If I `pip install rsa`, I no longer get a crash.

**Comment by busunkim96** [comment] 2021-03-12 16:21
Hi @michaelblyons,

When I install `google-auth-oauthlib` `rsa` seems to be installed as expected. Could you try this as well?
1. `python3 -m venv env`
2. `source env/bin/activate`
3. `pip install google-auth-oauthlib`
4. `pip freeze`

```cachetools==4.2.1
certifi==2020.12.5
chardet==4.0.0
google-auth==1.24.0
google-auth-oauthlib==0.4.3
idna==2.10
oauthlib==3.1.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7
six==1.15.0
urllib3==1.26.3
```

I can reproduce this the failure from `python -c "from google.auth.crypt import _cryptography_rsa"` but I think that is actually because `cryptography` is not installed. `python -c "from google.auth.crypt import _python_rsa"` (which uses the `rsa` package) seems to work fine.

`cryptography` is faster than `rsa`. If you're able to install that package in your environment I'd recommend taking advantage of it. https://github.com/googleapis/google-auth-library-python/blob/d80c85f285ae1a44ddc5a5d94a66e065a79f6d19/google/auth/crypt/_cryptography_rsa.py#L15-L20

https://github.com/googleapis/google-auth-library-python/blob/d80c85f285ae1a44ddc5a5d94a66e065a79f6d19/google/auth/crypt/rsa.py#L18-L30

**Comment by mik-laj** [comment] 2021-05-21 17:09
```
$ docker run --rm -ti python:3.9-slim-buster bash -c "pip install google-auth-oauthlib &>/dev/null; pip freeze"

cachetools==4.2.2
certifi==2020.12.5
chardet==4.0.0
google-auth==1.30.0
google-auth-oauthlib==0.4.4
idna==2.10
oauthlib==3.1.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7.2
six==1.16.0```

**Comment by busunkim96** [comment] 2021-05-21 17:21
Thanks for the repro @mik-laj!

@michaelblyons Since this issue has not had activity for over a month I am going to go ahead and close it. Please open a new issue if you are still experiencing problems.

**Closed by busunkim96** 2021-05-21 17:21 UTC
Labels: type: question
