### ISSUE TITLE
401 Request had invalid authentication credentials. Seems maybe creds aren't refreshing often enough?

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-auth-library-python#712] opened 2021-03-01 20:20 UTC
https://github.com/googleapis/python-firestore/issues/130

We have reports for firestore that containers that go idle and come back are having expired auth. It seems this may be an issue in this library?

### Steps to reproduce
This is a very weird one to reproduce. What is happening is that I deploy my docker container to Google Cloud Run and for some time everything works fine. I do successfully connect to the Firestore and retrieve data. After some point though things stop working and I get a Exception: 401 Request had invalid authentication credentials.

So very broad steps would be

Deploy a container in Google Cloud run
Execute some requests to Firestore. They should be successful
Wait some time (the container will go into hibernate as that point if you don't have enough traffic)
Throw some more requests to Firestore. Watch it fail.

**Comment by busunkim96** [comment] 2021-03-02 17:14
Hmm that's odd. I assume they're using the default service account that's attached to the instance? https://cloud.google.com/run/docs/securing/service-identity

`before_request` gets called on every request, and it checks if the credential is still valid. If it's not valid, the credentials are (supposed to be) refreshed. 


https://github.com/googleapis/google-auth-library-python/blob/91ee7a1b634c15ed65130a7666eaee1b9a2b908b/google/auth/transport/grpc.py#L69-L94

https://github.com/googleapis/google-auth-library-python/blob/91ee7a1b634c15ed65130a7666eaee1b9a2b908b/google/auth/credentials.py#L115-L134

https://github.com/googleapis/google-auth-library-python/blob/91ee7a1b634c15ed65130a7666eaee1b9a2b908b/google/auth/compute_engine/credentials.py#L97-L117

Perhaps there's something off with the expiration... @arithmetic1728 could you also take a look?

https://github.com/googleapis/google-auth-library-python/blob/91ee7a1b634c15ed65130a7666eaee1b9a2b908b/google/auth/credentials.py#L55-L78

https://github.com/googleapis/google-auth-library-python/blob/91ee7a1b634c15ed65130a7666eaee1b9a2b908b/google/auth/compute_engine/_metadata.py#L237-L267

**Comment by crwilcox** [comment] 2021-03-02 18:49
How does this interact with a stream that is hibernated? Is it possible they were mid request? I am not sure if this using streaming calls, but can look into it.

**Comment by busunkim96** [comment] 2021-03-02 18:52
Ah streaming! Good to know. I'm not sure where the refreshing would happen with a streaming request

**Comment by arithmetic1728** [comment] 2021-03-02 21:08
Where is the `stream()` method defined? Sorry I know nothing about streaming.

**Comment by busunkim96** [comment] 2021-03-02 22:04
Looks like https://github.com/googleapis/python-firestore/blob/0ae32cea8aa344825d29cc040069777162647780/google/cloud/firestore_v1/collection.py#L171-L209

**Comment by crwilcox** [comment] 2021-03-11 20:47
Updates have come in on the issue that spawned this. It seems the case is

1) start stream in cloud run (really any container)
2) suspend/pause for > 60 minutres
3) unpause
4) fails.

This is likely due to the credentials attached to the stream are now stale and haven't been refreshed.

**Comment by busunkim96** [comment] 2021-09-02 22:21
Looping back to this. I checked with gRPC folks on credential refresh for streams and got this response:

https://groups.google.com/g/grpc-io/c/5rOhCcqyHng

> Based on code, AuthMetadataPlugin fetches and injects the access token to headers (or initial metadata). 
>
> For every RPC, unary or streaming, the initial metadata will only be sent once. So, normally, the backend validates the token when it receives the request, and the RPC is allowed to run for arbitrary amount of time.
> 
> Unless, the backend or one of the proxy has an aggressive cut-off mechanism to abort the RPC with UNAUTHENTICATED(16) and with the text message in #712.
> 
> In short, it's more likely this error is generated at the beginning of RPC instead of in the middle.
> 
> ---
> 
> As for refresh credentials,  I saw the `CLOCK_SKEW`. So, there should not be invalid token when the client sent out the request. Is it possible that the first frame of the RPC lagged for 10s, so the server received an out-of-date access token? I guess we will need trace log to find out the root cause. Users can set `GRPC_TRACE=plugin_credentials` to see more details.

It's not immediately clear to me what suspending/pausing the container does to the client or stream... I will try to properly repro this myself following the info in the Firestore issue.

**Comment by busunkim96** [comment] 2021-09-10 21:10
Per my comments in https://github.com/googleapis/python-firestore/issues/130#issuecomment-914479063, it doesn't look like they were mid-request when the container went idle. But according to the gRPC folks, even if a stream were to go idle for a while it's not likely that the credential expiring would be an issue, since the token validation is done at the beginning of the stream.

Without more details on the specific scenario that's causing the 401 in the source issue (https://github.com/googleapis/python-firestore/issues/130) I don't think I can reproduce this, so I'm going to close it for now.

If more details are available please let me know and I will investigate further!

**Closed by busunkim96** 2021-09-10 21:10 UTC
Labels: priority: p2, type: bug
