### ISSUE TITLE
TransportError: ('Connection aborted.', BadStatusLine("''",))

### ISSUE THREAD

**Issue by erickertz** [googleapis/google-auth-library-python#436] opened 2020-01-27 21:42 UTC
#### Environment details

  - OS: Alpine3.9
  - Python version: 2.7.15 (sorry)
  - pip version: 19.0.3
  - `google-auth` version: 1.11.0
  - `google-cloud-pubsub` version: 0.33.1

#### Steps to reproduce

I want to apologize for being on such old versions of Python and google-cloud-pubsu libs. I am working on updating both but will be behind for a little while.

  1. I only see this error when sending a high volume of messages to PubSub from my Python Celery application. I auth with a service account and from_service_account_info method. Under constant high volumes I am seeing a steady log of the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/grpc/_plugin_wrapping.py", line 79, in __call__
    callback_state, callback))
  File "/usr/local/lib/python2.7/site-packages/google/auth/transport/grpc.py", line 77, in __call__
    callback(self._get_authorization_headers(context), None)
  File "/usr/local/lib/python2.7/site-packages/google/auth/transport/grpc.py", line 64, in _get_authorization_headers
    self._request, context.method_name, context.service_url, headers
  File "/usr/local/lib/python2.7/site-packages/google/auth/credentials.py", line 124, in before_request
    self.refresh(request)
  File "/usr/local/lib/python2.7/site-packages/google/oauth2/service_account.py", line 334, in refresh
    access_token, expiry, _ = _client.jwt_grant(request, self._token_uri, assertion)
  File "/usr/local/lib/python2.7/site-packages/google/oauth2/_client.py", line 149, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/usr/local/lib/python2.7/site-packages/google/oauth2/_client.py", line 105, in _token_endpoint_request
    response = request(method="POST", url=token_uri, headers=headers, body=body)
  File "/usr/local/lib/python2.7/site-packages/google/auth/transport/requests.py", line 128, in __call__
    six.raise_from(new_exc, caught_exc)
  File "/usr/local/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
TransportError: ('Connection aborted.', BadStatusLine("''",))
```

I also see from time to time a similar Transport error:

`TransportError: ('Connection aborted.', error(0, 'Error'))`

Not sure if the two are related. I also came across another similar reported issue:

https://github.com/googleapis/google-auth-library-python/issues/246

Since my Celery app is non stop processing thousands of messages, I'm not sure if manually refreshing the token for each message will help.

Thanks in advance for any help!

**Comment by busunkim96** [comment] 2020-01-27 21:57
Do you see the errors listed in console.cloud.google.com?

Are you also sending concurrent requests as in #246? Any bits of code you can provide would be helpful. :)

CC @anguillanneuf @plamut in case they've seen anything similar.

**Comment by erickertz** [comment] 2020-01-27 22:01
I actually didn't realize that google-auth was updated to 1.11.0, just updated my original ticket.

**Comment by erickertz** [comment] 2020-01-27 22:12
@busunkim96 yes, there is a high level of concurrency in the application. It is a Celery application with many workers that is constantly pulling messages from AWS and then publishing to PubSub. I will take a look at the cloud console and report back. 

Here is some code we have in a wrapper class where the PublisherClient is instantiated:

```
class PubSubManager(object):
    """
    Class to instantiate a manager class which interacts with the Google pubsub service.
    This class uses a factory pattern to post messages to brand-specific topics.

    https://cloud.google.com/pubsub/docs/overview
    https://cloud.google.com/pubsub/docs/reference/libraries#client-libraries-install-python

    The client uses batching via batch_max_bytes and batch_max_latency settings in settings.yaml
    https://cloud.google.com/pubsub/docs/publisher#batching-to-balance-latency-and-throughput
    """

    def __init__(self, publisher_client=None, logger=None):
        self.publisher_client = publisher_client
        if not publisher_client:
            # Credentials are stored in the environment in str form
            raw_creds = os.environ.get("XXXXXXXXXXX")
            if raw_creds:
                # Convert the cred string to json, replacing any newlines and carriage returns
                json_creds = json.loads(raw_creds.replace("\r\n", ""), strict=False)

                # Build credentials from the json object
                creds = service_account.Credentials.from_service_account_info(json_creds, scopes=PubSubSettings.SCOPES)
                self.publisher_client = pubsub.PublisherClient(credentials=creds,
                                                               batch_settings=PubSubSettings.BATCH_SETTINGS)
            else:
                self.publisher_client = pubsub.PublisherClient(batch_settings=PubSubSettings.BATCH_SETTINGS)

        self.logger = logger or logging.getLogger(self.__class__.__name__) 
```

This class is then injected into several other handlers that continuously process a large volume of messages.

**Comment by erickertz** [comment] 2020-01-28 01:20
@busunkim96 I guess my biggest concern is that I'm unsure if these errors are preventing the messages to get to PubSub. Is there retry logic when this occurs, or do they overall not have any effect on the PubSub client?

I'm also not seeing out of the ordinary in the cloud console. Thanks again for your help.

**Comment by plamut** [comment] 2020-01-28 07:13
Speaking of PubSub - this is the first time I see such error, cannot say what causes it from the top of my head.

BTW, is there a reason for not using one of the more recent version of the PubSub client? Version 0.33.1 is almost two years old now, and a lot has been fixed in the meantime (at the time of writing the latest release still supports Python 2.7). Though this issue does seem to be caused by something else...

**Comment by erickertz** [comment] 2020-01-28 14:10
@plamut There is no particular reason for the old pubsub version. This application has been around for some time and it simply hasn't been updated. I'm going to update to latest soon and will post back, though as you said, this does seem to be caused by something else. Thanks.

**Comment by plamut** [comment] 2020-01-28 18:47
@erickertz Just a thought - is the client instance, by an chance, shared between multiple threads?

Asking because the client's underlying gRPC transport is not thread-safe and weird things can happen if multiple threads use it at the same time.

**Comment by erickertz** [comment] 2020-01-28 22:22
> @erickertz Just a thought - is the client instance, by an chance, shared between multiple threads?
> 

@plamut yes, this is being used by a Celery application that has multiple workers and threads.

**Comment by plamut** [comment] 2020-01-29 07:15
@erickertz In that case it would be best to create a client instance in each worker, and not share the instances between threads, at least not without any synchronization. Please let us know if that solves the problem.

**Comment by erickertz** [comment] 2020-04-21 13:36
@plamut looping back around to this old ticket. I ended up switching the Celery execution pools to prefork from gevent and the problem stopped. I guess the auth lib didn't play nicely with the green threads.

**Comment by plamut** [comment] 2020-04-21 13:50
@erickertz Thanks for the update! It's good that you found a way around the issue.

@busunkim96 While it would be nice to come to the bottom of this, it appears to be deployment-specific and thus hard to reproduce on our side. Do we want to close this, or keep it open, nevertheless?

**Comment by erickertz** [comment] 2020-04-21 15:00
For what its worth, I'll bet if you wrote up a script that fired up a bunch of threads and shared the same Auth client you could reproduce. My issue in particular was using the PubSub client and under a decent amount of volume sending messages to PubSub I saw the underlying Auth Error. Let me know if I can help any further. Thanks again.

**Comment by busunkim96** [comment] 2020-04-21 22:03
@plamut Closing this for now, but we can revisit it in a future issue if it's impacting a lot of people.

**Closed by busunkim96** 2020-04-21 22:03 UTC
Labels: status:awaiting information, type: question
