### ISSUE TITLE
Authentication priority issue with fetch_id_token

### ISSUE THREAD

**Issue by jceresini** [googleapis/google-auth-library-python#747] opened 2021-05-05 17:20 UTC
According to the Google Cloud documentation, the environment variable `GOOGLE_APPLICATION_CREDENTIALS` takes priority over environment-specific credentials such as a compute instance's service account:

https://cloud.google.com/docs/authentication/production

> 
> Additionally, we recommend you use Google Cloud Client Libraries for your application. Google Cloud Client Libraries use a library called Application Default Credentials (ADC) to automatically find your service account credentials. ADC looks for service account credentials in the following order:
> 
>     If the environment variable GOOGLE_APPLICATION_CREDENTIALS is set, ADC uses the service account key or configuration file that the variable points to.
> 
>     If the environment variable GOOGLE_APPLICATION_CREDENTIALS isn't set, ADC uses the service account that is attached to the resource that is running your code.
> 
>     This service account might be a default service account provided by Compute Engine, Google Kubernetes Engine, App Engine, Cloud Run, or Cloud Functions. It might also be a user-managed service account that you created.
> 
>     If ADC can't use any of the above credentials, an error occurs.

However if you use `google.oauth2.id_token.fetch_id_token`, it always favors the environment's credentials:

https://github.com/googleapis/google-auth-library-python/blob/master/google/oauth2/id_token.py#L179

```
    # 1. First try to fetch ID token from metada server if it exists. The code
    # works for GAE and Cloud Run metadata server as well.
    [...]

    # 2. Try to use service account credentials to get ID token.

    # Try to get credentials from the GOOGLE_APPLICATION_CREDENTIALS environment
    # variable.
```

**Comment by arithmetic1728** [comment] 2021-05-05 19:21
duplicate of #663

**Comment by jceresini** [comment] 2021-05-05 20:18
The other issue talks about an exception being raised. I'm saying the order is backwards from the documented credentials lookup order.

**Closed** 2021-07-14 18:40 UTC
Labels: type: question
