### ISSUE TITLE
service_account.Credentials: Retry on errors from oauth2.googleapis.com

### ISSUE THREAD

**Issue by evanj** [googleapis/google-auth-library-python#343] opened 2019-05-30 17:29 UTC
It appears that the current implementation of the `service_account.Credentials` object will only try to refresh the service account credentials once, then raise an exception if it fails. I might be misunderstanding from looking at the code and our log messages, but I can't see where it does any retries. It would probably be helpful if it did.

The `requests.AuthorizedSession` and `urllib3.AuthorizedHttp` classes *do* seem to do retries, using the `DEFAULT_MAX_REFRESH_ATTEMPTS` variable. However, `grpc_helpers.create_channel` just constructs `google.auth.transport.requests.Request()`, which constructs `requests.Session()` directly.

### Details

We recently hit a few exceptions in a production service using Google Cloud APIs, running in Google Cloud. The log messages and stack trace are below. It appears that `oauth2.googleapis.com` hit some sort of temporary error, and rather than retrying, it just gives up. Our application got an exception while trying to call a Google Cloud API. Retrying seems to be the right solution here.

### Log and stack trace

This shows the application trying to refresh the token when it makes a KMS API call, the refresh failing, then the application getting a failed request. A retry would have masked these errors.

```
2019-05-29 14:46:20.140 EDT: google.auth.transport.requests: Making request: POST https://oauth2.googleapis.com/token"   
2019-05-29 14:46:20.142 EDT: urllib3.connectionpool: Resetting dropped connection: oauth2.googleapis.com
2019-05-29 14:46:20.197 EDT: urllib3.connectionpool: https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 503 None
2019-05-29 14:46:20.200 EDT: grpc._plugin_wrapping: AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f684bfcd3d0>" raised exception!

Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/grpc/_plugin_wrapping.py", line 79, in __call__
    callback_state, callback))
  File "/venv/local/lib/python2.7/site-packages/google/auth/transport/grpc.py", line 77, in __call__
    callback(self._get_authorization_headers(context), None)
  File "/venv/local/lib/python2.7/site-packages/google/auth/transport/grpc.py", line 65, in _get_authorization_headers
    headers)
  File "/venv/local/lib/python2.7/site-packages/google/auth/credentials.py", line 122, in before_request
    self.refresh(request)
  File "/venv/local/lib/python2.7/site-packages/google/oauth2/service_account.py", line 322, in refresh
    request, self._token_uri, assertion)
  File "/venv/local/lib/python2.7/site-packages/google/oauth2/_client.py", line 145, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/venv/local/lib/python2.7/site-packages/google/oauth2/_client.py", line 111, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/venv/local/lib/python2.7/site-packages/google/oauth2/_client.py", line 61, in _handle_error_response
    error_details, response_body)
RefreshError: ('internal_failure: None', u'{\n  "error": "internal_failure"\n}')


2019-05-29 14:46:20.203 EDT: (application-specific exception details removed)

Traceback (most recent call last):
...
  File "/venv/local/lib/python2.7/site-packages/google/cloud/kms_v1/gapic/key_management_service_client.py", line 1370, in decrypt
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/venv/local/lib/python2.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/venv/local/lib/python2.7/site-packages/google/api_core/retry.py", line 270, in retry_wrapped_func
    on_error=on_error,
  File "/venv/local/lib/python2.7/site-packages/google/api_core/retry.py", line 179, in retry_target
    return target()
  File "/venv/local/lib/python2.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/venv/local/lib/python2.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "/venv/local/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
ServiceUnavailable: 503 Getting metadata from plugin failed with error: ('internal_failure: None', u'{\n  "error": "internal_failure"\n}')"   
```

**Comment by evanj** [comment] 2019-06-03 16:32
We hit this again with some DNS weirdness that occurred. This has a slightly different stack trace and ultimate exception, but the same root cause: by default, it appears requests to oauth2.googleapis.com are not retried. From the Request documentation: "By default, Requests does not retry failed connections." I *think* from our logs and from looking through the code this is true, but there are a bunch of layers here so I might be wrong.


### Stack trace

```

```



### Initialization path:

* `google.api_core.grpc_helpers.create_channel()` (line 186)
    * creates `google.auth.transport.requests.Request()`; passes it to AuthMetadataPlugin
* `google.auth.transport.grpc.AuthMetadataPlugin.__init__()` assigns self._request
* `google.auth.transport.requests.Request.__init__()` (line 90)
    * creates requests.Session(); assigns it to self.session
* `requests.Session.__init__()`:
    * creates HTTPAdapter() for both http and https
* `requests.Session.__init__()`:
    * creates requests.adapters.HTTPAdapter() for both http and https
* `requests.adapters.HTTPAdapter.__init__()`:
    * creates self.max_retries = urllib3.util.retry.Retry(0, read=False)


### Call path:

* `google.auth.transport.grpc.AuthMetadataPlugin._get_authorization_headers` (line 61)
    * calls self._credentials.before_request(self._request, ...)
* `google.auth.credentials.Credentials.before_request` (line 122)
    * calls self.refresh(request)
* `service_account.Credentials.refresh()` (line 321)
    * calls google.oauth2._client.jwt_grant(refresh, ...)
* `google.oauth2._client.jwt_grant` (line 145)
    * calls google.oauth2._client._token_endpoint_request(request, ...)
* `google.oauth2._client._token_endpoint_request` (line 105)
    * calls request(...)
* `google.auth.transport.requests.Request.__call__` (line 118):
    * calls self.session.request(), which is a requests.Session.request

**Comment by busunkim96** [comment] 2020-01-10 01:15
@evanj Thank you for writing such a detailed issue!

It looks like `google.oauth2._client._token_endpoint_request` is retrying the request up to two times when the error message has something about an `internal_failure`.

https://github.com/googleapis/google-auth-library-python/blob/af29c1a9fd9282b38867961e4053f74f018a3815/google/oauth2/_client.py#L81-L126

I'm going to close this for now, but please do open a new issue if you continue to experience this. We may need to think about increasing the number of retries if that's the case.

**Closed by busunkim96** 2020-01-10 01:15 UTC
Labels: :rotating_light:, priority: p2, type: bug

**Comment by NehaThakur16** [comment] 2020-05-11 10:46
I am facing same issue : 
C:\Users\nehatha\AppData\Local\Programs\Python\Python38\python.exe C:/Users/nehatha/PycharmProjects/validateemail/validateGmail.py
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=72415299456-34v8p99iic9bsu4t4eqi3ju82moidjeo.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A3974%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgmail.readonly&state=xops7y0AWEDrNFvWy4nY2sQIpdJoaw&access_type=offline
Traceback (most recent call last):
  File "C:\Users\nehatha\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\nehatha\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\nehatha\AppData\Local\Programs\Python\Python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nehatha\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\nehatha\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\nehatha\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "C:\Users\nehatha\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 308, in connect
    conn = self._new_conn()
  File "C:\Users\nehatha\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000024BDAD49730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nehatha\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\nehatha\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "C:\Users\nehatha\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024BDAD49730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/nehatha/PycharmProjects/validateemail/validateGmail.py", line 49, in <module>
    service_val = get_service()
  File "C:/Users/nehatha/PycharmProjects/validateemail/validateGmail.py", line 40, in get_service
    creds = flow.run_local_server(success_message='test', port=0)
  File "C:\Users\nehatha\AppData\Local\Programs\Python\Python38\lib\site-packages\google_auth_oauthlib\flow.py", line 460, in run_local_server
    self.fetch_token(authorization_response=authorization_response)
  File "C:\Users\nehatha\AppData\Local\Programs\Python\Python38\lib\site-packages\google_auth_oauthlib\flow.py", line 280, in fetch_token
    return self.oauth2session.fetch_token(
  File "C:\Users\nehatha\AppData\Local\Programs\Python\Python38\lib\site-packages\requests_oauthlib\oauth2_session.py", line 336, in fetch_token
    r = self.request(
  File "C:\Users\nehatha\AppData\Local\Programs\Python\Python38\lib\site-packages\requests_oauthlib\oauth2_session.py", line 515, in request
    return super(OAuth2Session, self).request(
  File "C:\Users\nehatha\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\nehatha\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\nehatha\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024BDAD49730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

Process finished with exit code 1

**Comment by rohiramesh** [comment] 2022-07-06 06:11
gcloud components update resolved my issue
